changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{.Version}}](https://github.com/OpsLevel/cli/compare/{{.PreviousVersion}}...{{.Version}}) - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
kinds:
- label: Feature
- label: Refactor
- label: Deprecated
- label: Removed
- label: Bugfix
- label: Docs
- label: Security
