changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{.Time.Format "January 02, 2006"}}]((https://github.com/OpsLevel/cli/compare/{{.PreviousVersion}}...{{.Version}}))'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
footerFormat: |
  ## Docker Image

    - `docker pull public.ecr.aws/opslevel/cli:{{.Version}}`
kinds:
- label: Bugfix
- label: Feature
- label: Security
- label: Refactor
- label: Deprecated
- label: Removed
- label: Docs
- label: Dependency
