run:
  timeout: 2m
linters-settings:
  custom:
    nilaway_config:
      path: ./bin/nilaway_config.so
      description: self-built nilaway plugin
      original-url: github.com/nilaway_config-plugin
      settings:
        pretty-print: false

    nilaway:
      path: ./bin/nilaway.so
      description: self-built nilaway plugin
      original-url: github.com/nilaway-plugin

  errcheck:
    exclude-functions:
      - (*encoding/csv.Writer).Write
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
      - (*github.com/spf13/pflag.PFlagSet).GetString
      - (*os.File).WriteString
      - github.com/spf13/viper.BindEnv
      - github.com/spf13/viper.BindPFlags
      - github.com/spf13/viper.ReadConfig
      - github.com/spf13/viper.ReadInConfig
      - github.com/spf13/viper.Unmarshal
  staticcheck:
    checks: ["all", "-SA5001"]

#issues:
#  exclude-rules:
#    - linters:
#        - nilaway
#      path: "cmd/terraform.go"
