# https://taskfile.dev/

version: '3'

env:
  SRC_DIR: "{{.TASKFILE_DIR}}/src"

tasks:
  lint:
    desc: Formatting and linting
    dir: "{{.SRC_DIR}}"
    cmds:
      - gofmt -d .
      - go vet ./...
      - golangci-lint run

  lintfix:
    desc: Fix formatting and linting
    dir: "{{.SRC_DIR}}"
    cmds:
      - gofmt -w .
      - go mod tidy
      - golangci-lint run --fix

  test:
    desc: Run tests
    dir: "{{.SRC_DIR}}"
    cmds:
      - go test -v ./... {{ .CLI_ARGS }}
    silent: true

  workspace:
    desc: Setup workspace for local opslevel-go development
    dir: "{{.SRC_DIR}}"
    cmds:
      - git submodule update --init
        # The ":" is a no-op that keeps things rolling
      - go work init || ":"
      - go work use . submodules/opslevel-go
      - echo "Workspace ready!"
