# https://taskfile.dev/

version: '3'

tasks:
  lint:
    desc: Formatting and linting
    dir: src
    cmds:
      - gofmt -d .
      - go vet ./...
      - golangci-lint run

  lintfix:
    desc: Fix formatting and linting
    dir: src
    cmds:
      - gofmt -w .
      - go vet ./...
      - golangci-lint run --fix

  test:
    desc: Run tests
    dir: src
    cmds:
      - go test -v ./... {{ .CLI_ARGS }}
    silent: true
