project_name: opslevel
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/opslevel/cli/cmd.version={{.Version}}'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: cli
    homepage: "https://www.opslevel.com/"
    description: "Opslevel Command Line Utility"
    license: "MIT"
    folder: Formula
    dependencies:
      - name: jq
    install: |
      bin.install "opslevel"
    test: |
      system "#{bin}/opslevel version"
    tap:
      owner: opslevel
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
checksum:
  name_template: '{{ .ProjectName }}.sha256'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  skip: true
