project_name: opslevel
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goos:
      - windows
      - linux
      - darwin
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
dockers:
  - image_templates:
    - "public.ecr.aws/opslevel/cli:{{ .Tag }}"
    build_flag_templates:
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Tag }}"
    - "--build-arg=VERSION={{ .Tag }}"
nfpms:
  - formats:
      - deb
      - rpm
    dependencies:
      - jq
    vendor: "opslevel"
    homepage: "https://opslevel.com"
    maintainer: "OpsLevel <info@opslevel.com>"
    description: "Opslevel Command Line Utility"
    license: "Apache-2.0"
    file_name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: cli
    homepage: "https://www.opslevel.com/"
    description: "Opslevel Command Line Utility"
    license: "MIT"
    folder: Formula
    dependencies:
      - name: jq
    install: |
      bin.install "opslevel"
    test: |
      system "#{bin}/opslevel version"
    tap:
      owner: opslevel
      name: homebrew-tap
      token: "{{ .Env.ORG_GITHUB_TOKEN }}"
checksum:
  name_template: '{{ .ProjectName }}.sha256'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: desc
  filters:
    exclude:
      - "^Merge"
