name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**.go'
      - 'go.mod'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run quality checks and test code
        run: task ci
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./src/coverage.txt
          fail_ci_if_error: false
          verbose: true
